services:
  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      VERSION: '1.21.95.1'
    ports:
      - "19132:19132/udp"
    volumes:
      - mc-bedrock-data:/data
    stdin_open: true
    tty: true

  unmined-cli:
    build:
      context: .
      dockerfile: unmined-cli/Dockerfile
    volumes:
      - mc-bedrock-data:/data
      - ./minimap-backup:/minimap
    depends_on:
      minecraft-bedrock-server:
        condition: service_healthy

  mini-map-server:
    build:
      context: .
      dockerfile: http-server/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./minimap-backup:/minimap
    depends_on:
      unmined-cli:
        condition: service_started
      minecraft-bedrock-server:
        condition: service_healthy

volumes:
  mc-bedrock-data:
