services:
  minecraft-bedrock-server:
    image: itzg/minecraft-bedrock-server
    environment:
      EULA: "TRUE"
      VERSION: '1.21.95.1'
    ports:
      - "19133:19133/udp"
    volumes:
      - mc-bedrock-data-1:/data
    stdin_open: true
    tty: true


  unmined-cli:
    build:
      context: .
      dockerfile: unmined-cli/Dockerfile
    volumes:
      - mc-bedrock-data-1:/data
      - minimap:/minimap
    depends_on:
      minecraft-bedrock-server:
        condition: service_healthy

volumes:
  mc-bedrock-data-1:
